# fly.toml file generated for protohackers-yulian on 2022-09-09T00:50:41-07:00

app = "protohackers-yulian"
kill_signal = "SIGINT"
kill_timeout = 5

[env]

[[services]]
  internal_port = 10001
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    port = 10001

[[services]]
  internal_port = 10002
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    port = 10002

[[services]]
  internal_port = 10003
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    port = 10003

[[services]]
  internal_port = 10004
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    port = 10004

[[services]]
  internal_port = 10005
  protocol = "udp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    port = 10005

[[services]]
  internal_port = 10006
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    port = 10006

[[services]]
  internal_port = 10007
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 200
    soft_limit = 150
    type = "connections"

  [[services.ports]]
    port = 10007

[[services]]
  internal_port = 10008
  protocol = "udp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    port = 10008